name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      # 检出代码
      - uses: actions/checkout@v4

      # 安装 Rust 工具链
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly

      # 构建项目
      - name: Build
        run: cargo +nightly build --verbose

      # 运行测试
      - name: Run tests
        run: cargo +nightly test --verbose

      # 上传构建产物
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: edit-build-artifacts-${{ matrix.os }}
          path: |
            ${{ runner.os == 'Windows' && 'target/debug/edit.exe' || '' }}
            ${{ runner.os == 'Linux' && 'target/debug/edit' || '' }}
            ${{ runner.os == 'macOS' && 'target/debug/edit' || '' }}
